config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#home"
  get "success", to: "pages#success"


  post "select_product" => "pages#select_product"
  get "confirm" => "pages#confirm"

  post "send_data" => "pages#send_data"
  get "success" => "pages#success"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer, class_name: 'User', foreign_key: :customer_id
    has_many :order_items
    has_many :products, through: :order_items
    has_one :payment
    validates :total_amount, :status, presence: true
  end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :order
    belongs_to :product
    validates :quantity, :price, presence: true
  end

app/models/payment.rb
class Payment < ApplicationRecord
    belongs_to :order
    validates :status, presence: true
  end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :seller, class_name: 'User', foreign_key: :seller_id
    has_many :order_items
    has_many :orders, through: :order_items
    validates :name, :price, :stock_quantity, presence: true
  end

app/models/user.rb
class User < ApplicationRecord
    has_many :products, foreign_key: :seller_id
    has_many :orders, foreign_key: :customer_id
    validates :first_name, :last_name, :email, :role, presence: true
    validates :email, uniqueness: true
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @products = [
      { "id": 1, "name": "กระบอกน้ำ Odds" },
      { "id": 2, "name": "เสื้อโปโล Versions 3" },
      { "id": 3, "name": "เสื้อยืด Odds Versions 2" },
      { "id": 4, "name": "แก้วน้ำ" },
      { "id": 5, "name": "กระเป๋าออกกำลังกาย" },
      { "id": 6, "name": "หมวก" },
      { "id": 7, "name": "เสื้อวิ่ง" },
      { "id": 8, "name": "พวงกุญแจ" },
      { "id": 9, "name": "ถุงผ้า" },
      { "id": 10, "name": "ถุงเท้า" },
      { "id": 11, "name": "ยาดม" },
      { "id": 12, "name": "สมุด" },
      { "id": 13, "name": "ปากกา" },
      { "id": 14, "name": "ดินสอ" },
      { "id": 15, "name": "ผ้าบัฟ" },
      { "id": 16, "name": "ขวดน้ำออกกำลังกาย" }
    ]
  end

  def select_product
    selected_product_id = params[:product_id]
    if selected_product_id.present?
      session[:selected_product_id] = selected_product_id
      redirect_to confirm_path
    else
      flash[:alert] = "No product selected"
      redirect_to root_path
    end
  end

  def confirm
    @product_id = session[:selected_product_id]
    redirect_to root_path if @product_id.to_i < 0
  end

  def send_data
    name = params[:name]
    phone = params[:phone]
    if name.present? && phone.present?
      flash[:notice] = "Data sent successfully"
      session[:name] = name
      session[:phone] = phone
      redirect_to success_path
    else
      flash[:alert] = "Name and phone number are required"
      redirect_to confirm_path
    end
  end

  def success
    @name = session[:name]
    @phone = session[:phone]
  end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="bg-gray-100">
  <head>
    <title><%= content_for(:title) || "Odds Market" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body class="w-full min-h-screen bg-white">
    <nav class="p-5 bg-black text-white text-xl font-semibold flex items-center justify-center fixed top-0 right-0 left-0">Odds Market</nav>
    <main class="w-full min-h-screen pt-16">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/confirm.html.erb
<div class="w-full mt-55 flex items-center justify-center">
  <div class="flex flex-col gap-12 items-center">
    <div class="flex flex-col gap-2 items-center">
      <h1 class="text-black text-xl font-semibold">กรอกข้อมูลผู้ซื้อ</h1>
    </div>
    
  <%= form_with url: send_data_path, method: :post, local: true do %>
  <div class="flex flex-col gap-5">
    <div class="flex gap-10 items-center">
      <label for="name" class="text-black text-xl ">Name:</label>
      <input type="text" name="name" id="name" required class="border rounded-[4px] border-black text-black text-xl px-3 py-2 w-100" placeholder="e.g. Jamesuklhor">
    </div>
    <div class="flex gap-17 items-center">
      <label for="phone" class="text-black text-xl ">Tel:</label>
      <input type="text" name="phone" id="phone" required class="border rounded-[4px] border-black text-black text-xl px-3 py-2 w-100" placeholder="e.g. 09999999999">
    </div>
  </div>
    <div class="w-full flex items-center justify-center mt-14">
      <button type="submit" class="px-3 py-2 bg-[#2AA6FF] text-white text-xl rounded-[4px]">Confirm</button>
    </div>
  <% end %>
  </div>
  
</div>

app/views/pages/home.html.erb
<div>
  <%# train %>
  <div class="mt-1 px-20 py-5 bg-black border-t border-t-white">
    <div class="flex flex-col gap-2">
      <span class="text-white font-semibold text-[36px]">Shop</span>
      <p class="text-white text-[18px]">Revamp your style with the latest designer trends in men’s<br> clothing or achieve a perfectly curated wardrobe thanks to<br/> our line-up of timeless pieces. </p>
    </div>
  </div>
  <%# train %>

  <%# List @products %>
  <%= form_with url: select_product_path, method: :post, local: true, html: { class: "flex flex-col w-xl mx-auto pb-16" } do %>
    <% @products
      .sort_by { |product| product[:name] }
      .each do |product| 
    %>
      <label class="p-4 mx-6 flex gap-4 border-b-2 border-gray-600" for="<%= product[:id] %>">
        <input type="radio" name="product_id" id="<%= product[:id] %>" value="<%= product[:id] %>">
        <span class="text-2xl"><%= product[:name] %></span>
      </label>
    <% end %>
    <button type="submit" class="px-4 py-2 mt-4 w-fit bg-blue-500 text-white self-center rounded-md">Buy</button>
  <% end %>
</div> 

app/views/pages/success.html.erb
<div class="flex flex-col items-center justify-center min-h-screen bg-gray-100">
  <div class="bg-white p-10 rounded-lg shadow-lg text-center">
    <h1 class="text-3xl font-bold text-green-600">สำเร็จ</h1>
    <p class="text-gray-700 mt-2 text-lg">
      การสั่งซื้อของคุณ <span class="font-semibold"><%= @name || "John Doe" %></span>
    </p>
    <p class="text-gray-700 text-lg">
      เบอร์โทร: <span class="font-semibold"><%= @phone || "0123456789" %></span>
    </p>

    <p class="text-gray-800 mt-4 text-lg">
      สามารถรับสินค้าได้ที่ <span class="font-semibold">ตึกทิปโก้ ชั้น 20</span><br>
      โดยจะมีการโทรนัดวันเวลาที่รับอีกครั้ง
    </p>

    <div class="flex flex-col items-center mt-8">
      <%= link_to "Back to Home", root_path, class: "px-6 py-3 bg-blue-500 text-white rounded-lg hover:bg-blue-600 transition" %>
    </div>
  </div>
</div>